### ISSUE TITLE
Legend clarifications

### ISSUE THREAD

**Issue by brmagnuson** [ucd-cws/drought-app#10]
Two potentially related issues:
-The squares are labeled 'Application'. Please change this to 'Appropriative'.
-What are the circles? I wonder if the squares are really 'Post-1914 Appropriative' and the circles 'Pre-1914 Appropriative', based on the naming structure: pre-1914 appropriative rights all start with an S like Riparian but

**Comment by jrmerz** [comment]
Yup, that is all correct.  I have been meaning to change.  lazy programmer.

**Comment by jrmerz** [comment]
Think it's fixed @ 0f992fd3d9ba3f61048047122c695dc2fe58c753.  Let me know if we can close.

**Comment by brmagnuson** [comment]
Yes, looks good!
