### ISSUE TITLE
 Calendar of Existing Points

### ISSUE THREAD

**Issue by qjhart** [ucd-cws/drought-app#11]
If we supplied the appropriate query (and what would that be?) can we have a calendar that shows what days are available for a particular watershed ?

**Comment by jrmerz** [comment]
It is possible to add a calendar widget if we have the query (as well as the data :) )

**Comment by qjhart** [comment]
Let me know what you'd like to see for a query.

**Comment by jrmerz** [comment]
let me know what you want to render :)  I'm assuming we are rendering by node?  At which point a query were we pass id and get next 7, 10, 30... days back?

**Comment by qjhart** [comment]
@jrmerz I was thinking more like this: http://watershed.ice.ucdavis.edu/vizsource/rest?view=available_allocations&tqx=out:html  But wonder if you want a JSON column as well mostly.

Or:
http://watershed.ice.ucdavis.edu/vizsource/rest?view=available_allocations&tq=WHERE+watershed=%27EEL%20RIVER%27&tqx=out:html

Or 
http://watershed.ice.ucdavis.edu/vizsource/rest?view=available_allocations&tq=WHERE+allocation_date%3E%272014-05-01%27&tqx=out:html

**Comment by jrmerz** [comment]
With the vizsource going away, I'm closing this.
