### ISSUE TITLE
Use same interface to allow an upload of a particular allocation run.

### ISSUE THREAD

**Issue by qjhart** [ucd-cws/drought-app#12]
Can we build a simple interface where an administrator can upload a particular allocation run to the server, so that it is publicly available.  I can think of two ways to do this: 
-  We build a postgres function that reads in a CSV, and then build a little script to upload the CSV.
-  (In the manner that with our new hammer, everything is a nail :) That would cause the submission of one CSV file as a pull request to a data repository.  This would allow anyone to sumbit, but requires an additional admin step to approve, and repopulate the DB.

**Comment by jrmerz** [comment]
Can you send me a sample CSV, I seemed to have lost mine.

**Comment by qjhart** [comment]
@brmagnuson We need some example allocation files to see about admining this drought-app.

**Comment by brmagnuson** [comment]
Am requesting these; will get them to you shortly.

**Comment by brmagnuson** [comment]
Sent you an example; let me know if you need more examples or anything else.

**Comment by jrmerz** [comment]
@qjhart is the calvindb repo (bitbucket) up to date and where I can find the latest code for the postgres calvin instance?  I want to make sure I am up to speed before I comment further.

**Comment by qjhart** [comment]
@jrmerz, the current drought stuff was integared directly in the calvindb bitbuck account, because originally there was some notion that they woud be together, but I don't think that's the case, and I think we can probably seperate it.   I wonder why not move it all  to this repo?

**Comment by jrmerz** [comment]
@qjhart what about moving to a data repo with csv files and sqlite backend as we have talked about before?  Both checked into repo.  Then all data is public and query-able.  Only issue would be if using pull requests is too complex.  Could there be a simpler way to add/update csv's?

**Comment by brmagnuson** [comment]
Just checking in on the status of this. The State Board is starting to murmur about getting started on porting the website over to their side rather than perpetually maintaining it at Davis, which I believe was the intent all along. I said you guys had some improvements you still wanted to make (mainly this issue) and I would check in and see how it was going.

**Comment by jrmerz** [comment]
@brmagnuson Perhaps this should be a new ticket, but here is the breakdown for transferring the application.

- Application assets (HTML, JS, CSS), basically everything in stored in this repository, needs to be hosted on a state server.
- The Postgres backend needs to be ported
- A Jetty/Tomcat/[Insert your java servlet server here] needs to be stood up
- The servlet server needs to host the custom Google Visualization Source build.  The PG connection will need to be configured as well.

The first item is easy.  Just pull this repo down and host it on any web server.  This will give you the main application as well as CSV upload and visualization.  The next 3 steps are for the 'query' functionality.  @qjhart do you want to chime in with more details on this?

Finally, we are still working out the solution for submitting data back to postgres instance (this ticket).  @qjhart I think we need to have a more formal discussion about this if that functionality is required for the transfer.

**Comment by qjhart** [comment]
Yes, I've copied some of this over to #15 , so we can discuss moving the service to SWRCB.
