### ISSUE TITLE
HUC 12 average not showing up for uploaded csv files

### ISSUE THREAD

**Issue by brmagnuson** [ucd-cws/drought-app#13]

**Comment by jrmerz** [comment]
There was two issue I found with file upload.  I have fixed both and pushed, the averages should show now.  All huc 12 data should have the column header HUC-12.

@qjhart It looks like some of the attribute names have changed in the database (ex: huc_12 is not HUC-12, water_right_type is now 'Right Type').  Can we post somewhere (perhaps wiki) current data structure and make issues when changes happen?  Just to make sure the app gets up to date as well.
