### ISSUE TITLE
Box vs. Google Drive

### ISSUE THREAD

**Issue by jrmerz** [ucd-cws/drought-app#16]
For hosting public CSV files it looks like both Box and Google Drive have API's that will work.  Though both require authentication to list contents of a folder.  The folders and files can be set to allow anyone to access (so no authorization) but to make the API calls to list contents, authentication is required.

I need to investigate a little further, but last I used Google Drive, if the you had the docid and the doc was public, you could access w/o authentication.  It looks like that authentication is required for retrieving a documents content in Box.  Obviously this still doesn't help the discovery issue stated above.

With this in mind, how would you like to proceed?

**Comment by qjhart** [comment]
Well shoot.  I guess in that case, I would say let's move forward pointing to an FTP site, and then I'll get some feedback at the Meeting on Aug 18th?  Alternatively, we could do a two-step, get a list of files from Google Drive, then parse that list for a set of CSV files.  The advantage to that I guess is we could add metadata.  What's strange, is that you don't have to be logged into Google to see dirs in the browser I thought.

**Comment by jrmerz** [comment]
FTP sounds like a possibility,  though I am not sure how to do this client side.  This (not the greatest) stackoverflow has more info: http://stackoverflow.com/questions/4594798/download-file-from-ftp-via-javascript

Both file list (https://developers.google.com/drive/v2/reference/files/list) and folder children (https://developers.google.com/drive/v2/reference/children/list) queries require authentication.  How do you propose getting list of files from google drive w/o login?

And yes, via the browser you can see public folders w/o login, via API, no.

**Comment by qjhart** [comment]
https://drive.google.com/open?id=1ACi7P0pOy-JRjtw6HribQphhEOZ-0-CkQ_mqnyCfJcI

From Folder:
https://drive.google.com/folderview?id=0B2gH34NLQLU-fnVaVmliUEk0MEVNWFEtY24tRHVrMUgycTdPN2dYdXB2eUpxYnNSNjZCdEU&usp=sharing

**Comment by jrmerz** [comment]
Ok, this will work if we just move to Google Spreadsheets.  I miss spoke earlier and you have to login to see data on Google Drive.

So the workflow would be: upload data to google sheets, then add a line the the central public spreadsheet.
