### ISSUE TITLE
Host for WMS services

### ISSUE THREAD

**Issue by jrmerz** [ucd-cws/drought-app#17]
Currently the watersheds and HUC 12 overlays are hosted on Google Maps Engine which is going away.  We need a place to host these services.

**Comment by jrmerz** [comment]
This might be a different issue, but perhaps we can use the solution we find above to help us... we also need a query for HUC-12 geometry.  This is required to render the HUC-12 averages on the map.  This query just needs to support get by id.

**Comment by qjhart** [comment]
These are currently located at: http://atlas.cws.ucdavis.edu/arcgis/rest/services/CalWater_Hydrologic_Unit/MapServer
and
http://atlas.cws.ucdavis.edu/arcgis/rest/services/Watersheds/MapServer

The watersheds map has WFS enabled for feature download.

**Comment by jrmerz** [comment]
Switched from google WMS services to CWS.  Pushed live.
