### ISSUE TITLE
Update Application for SWRCB access to POD data.

### ISSUE THREAD

**Issue by qjhart** [ucd-cws/drought-app#18]
Super.  I don't foresee any problems with that schedule.  For our application both the CalWater and HUC boundaries are simple linework, so I don't anticipate any symbology problems either.

Regarding the PODs.  We did our preliminary review for that, and I think everything will work just fine with the existing interface you have up. We can query the layer; http://gispublic.waterboards.ca.gov/arcgis/rest/services/Water_Rights/Points_of_Diversion/MapServer/0/query

and pull locations easily enough.   There is a 1000 point limit on your returns, but we can work with that fine.  I have to double check on how we managed applications with multiple PODs, but actually that's more of question for the modelers to be involved in, I think.

**Comment by jrmerz** [comment]
App Id lookup switched from UCD viz source to waterboards ArcGIS server.  Pushed live.
