### ISSUE TITLE
Make sure that the web app is working on IE9

### ISSUE THREAD

**Issue by brmagnuson** [ucd-cws/drought-app#7]

**Comment by jrmerz** [comment]
Some UI aspects will not work in IE 9 due to it's lack of standards support.  I see the popup doesn't show.  I will fix this.  It might be better to create new issues for other IE 9 specific bugs.

**Comment by brmagnuson** [comment]
This came up at a meeting with the state board in mid-March; when they opened the website up in IE it didn't show at all. They may have been running an out of date version (IE 8, which Quinn told me yesterday that we don't support since it's too old). I just want to make sure it's generally working in recent versions of IE; no specific issues.

**Comment by jrmerz** [comment]
Ok, I tested with Windows 7, using IE 11 (current) in IE 9 mode and only found one issue so far.  I'll download a IE 9 vm so I can verify.  Old IE is always a pain, but this app should be able to be supported in IE 9 without too much work.  I will create new issues as I find them.

**Comment by jrmerz** [comment]
Appears to be working at c5e7ae218a41a27fcd96af84dd3921f90781775c.  Will open new tickets as issues arise.
