### ISSUE TITLE
In the query interface, add some examples of how to search for a specific user and group of users

### ISSUE THREAD

**Issue by brmagnuson** [ucd-cws/drought-app#8]

**Comment by jrmerz** [comment]
@qjhart can you provide some nice examples and I will add them to the page?

**Comment by qjhart** [comment]
# Query Examples

In the following examples, these are called from the [query](http://watershed.ice.ucdavis.edu/drought/query.html) page.  Note, demand queries are most interesting, we currently don't pull out a lot of attributes for supply.

 For shorthand, the form is specified as:

| form | value |
| --- | --- |
| Table | Demand |
| Watershed | EEL RIVER |
| Date | 5-1-2014 |

With the Query changing.

| Desire | Query |
| --- | --- |
| One Application | SELECT \* WHERE application_number='A001719' |
| Large Riparian Demands, Descending | SELECT \* WHERE riparian = true and demand > 20 ORDER by demand desc |
| Latest Appropriative rights | SELECT \* WHERE water_right_type='Appropriative' and priority_date  > '1990-01-01'  order by priority_date desc |
| For a specific HUC | SELECT \* WHERE huc_12 = '180101050802' |

**Comment by jrmerz** [comment]
Examples are up.

**Comment by brmagnuson** [comment]
This looks great; just one further request to clarify:
I had trouble understanding this line: "With the form is specified as:". I had to go back to Quinn's example above to figure it out. I think this would be more clear: "With the above form specified as:" (dropping the is and adding the above).
Also, I would change the period after "With the Query changing." to a colon so that it matches the other instructional line.

**Comment by jrmerz** [comment]
@brmagnuson push changes.  Let me know if this is good to close.

**Comment by brmagnuson** [comment]
Looks good to close, other than I'm not seeing any of the changes in Chrome--does that just take another push later on once all the issues are closed?

**Comment by jrmerz** [comment]
@brmagnuson The changes were pushed yesterday.  Can you refresh your browser and let me know if you see the updates?

**Comment by brmagnuson** [comment]
That finally worked; I had to clear the cache, apparently. Thanks!
