### ISSUE TITLE
Add a toggle for 0 demands

### ISSUE THREAD

**Issue by qjhart** [ucd-cws/drought-app#9]
For applications that have a 0 demand (because of the season), we should be able to have a toggle in the legend that allows for these to be toggled on and off in terms of visibility.  Also, can we think of not having them match any of the colors in the shortage or met demand scales?

**Comment by brmagnuson** [comment]
This is a great idea! Maybe they could be hollow shapes (not filled in with a color or grey) when they are displayed on the map.

**Comment by jrmerz** [comment]
Hollow is good, but hard to show in the legend, they will just be white.  If we apply a color, they will really pop and my guess is that we want the opposite of that.....  hummm.

**Comment by qjhart** [comment]
They could also be an even smaller null sign, ∅

**Comment by jrmerz** [comment]
That should work... though the legend is rendered as canvas and map is svg.  Will verify I can create that icon in both.  Should be doable.

**Comment by jrmerz** [comment]
Added @ 0f992fd3d9ba3f61048047122c695dc2fe58c753.  pushed as well

**Comment by brmagnuson** [comment]
This cleans things up a lot! Looks much better. Any chance the null sign could be water-right-type specific? As is the null sign makes it look like all the zero-demand users are riparian because of the circle.

**Comment by jrmerz** [comment]
Ok, the empty nodes will now render as their type as well as empty.  This pushed me to rewrite the marker/icon rendering into a consolidated function using the canvas tag.  What this means, I might have broken some things, let me know if you see any badness.

**Comment by qjhart** [comment]
Looks good!
